version: '3.3'

services:

  web:
    build: ../../../PycharmProjects/untitled/test_MeduzZen
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/test_fastapi
    depends_on:
      - db

  db:
    image: postgres:11
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo